---
title: "Urbanization, energy consumption, and CO2 emissions with different income level countries"
author:
- familyname: Cui
  othernames: Di
  address: Monash University
  email: dcui0002@student.monash.edu
  correspondingauthor: true
  qualifications:  Master of Business Analytics
- familyname: Chen
  othernames: Guanru
  address: Monash University
  email: gche0054@student.monash.edu
  correspondingauthor: true
  qualifications: Master of Business Analytics
- familyname: Chen
  othernames: Yunzhi
  address: Monash University
  email: yche0537@student.monash.edu
  correspondingauthor: true
  qualifications:  Master of Business Analytics
department: TGIF \newline Di Cui &\newline Guanru Chen &\newline Yunzhi Chen
organization: World Bank
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  bookdown::pdf_document2:
    template: monashreport2.tex
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: false
---

```{r , echo = FALSE, message = FALSE, warning = FALSE}
# Libraries

library(tidyverse)
library(readr)
library(kableExtra)
library(bookdown)
library(gridExtra)
```

# Data set introduction



# Research questions



\clearpage

# Exploratory data analysis

\section*{Global meat production -- Di Cui}

```{r read-data1, echo = FALSE, message = FALSE, warning = FALSE}

```

\subsection*{Analysis} 

**Q1:**

**Q2:**


\clearpage





\section*{Citation}
The data set is cited from @Worldbank.

Analysis of the data is done using the following packages:

bookdown @bookdown1, @bookdown2,

tidyverse @tidyverse,

readr @readr,

kableExtra @kableExtra.